{
  "internalError": 1,
  "message": "User not found"
}